### ISSUE TITLE
Jugador - Si se mueve a un casillero ocupado el casillero original queda vacío

### ISSUE THREAD

**Issue by M-Picco** [ChrisEFS/TP2-AlgoCraft#4]
Ver [Jugador::mover](https://github.com/ChrisEFS/TP2-AlgoCraft/blob/Entrega_2/src/fiuba/algo3/tp2/jugador/Jugador.java#L42)

**Comment by alopezbizon** [comment]
Corregido en commit https://github.com/ChrisEFS/TP2-AlgoCraft/commit/daa0e665cfe04bfff1921c7925c570425b0e1e1b
